# -*- coding: utf-8 -*-
"""example

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5EnFeHIv9HsfdSafJYwXSe_x19fQZcu
"""

from datasets import Cora

dataset = Cora()

# >>>>>>>>>> test MEA

# mea = ModelExtractionAttack0(dataset, 0.25)
# mea.attack()


# >>>>>>>>>> test ImperceptibleWM
# from models.defense.OwnerWatermarkingDefense import OwnerWatermarkingDefense
# from utils.dglTopyg import dgl_to_pyg_data
#
# pyg_data = dgl_to_pyg_data(dataset.graph)
#
# defense = OwnerWatermarkingDefense(dataset)
# metrics = defense.defend(pyg_data)
#
# print(metrics)


# >>>>>>>>>> test ImperceptibleWM2
# from models.defense.ImperceptibleOwnerUniqueWatermark import WatermarkByBilevelOptimization
#
# defense = WatermarkByBilevelOptimization(dataset)
# defense.defend()


# >>>>>>>>>> test SurviveWM2
# from models.defense.SurviveWM2 import OptimizedWatermarkDefense
# from datasets import ENZYMES

# dataset = ENZYMES()
# defense = OptimizedWatermarkDefense(dataset, 0.25)
# defense.defend()


# >>>>>>>>>> test Link Steal Attack
from datasets import Cora
from pygip.attacks.link_steal_attack import LinkStealAttack

dataset = Cora()

attack = LinkStealAttack(dataset)
attack.configure(
    shadow_datasets=["dblp"],
    shadow_models=["graphsage"],
    attack_ids=[1],   # 1-hop attack
    props=[100],
    seed_num=3,
    gpu=0
)

results = attack.attack()
print(results)